language: cpp
os: linux
compiler: gcc

# addons:
  # apt:
   #  sources:
     #  - ubuntu-toolchain-r-test

# before_install:
  # - pip install --user cpp-coveralls
  
script: 
    # gcc ./amUtilities_UnitTest/main.cpp -o -l ./amUtilities_UnitTest/gtest.h
    return 0;