os: linux
sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  - echo "Creating build directory..."
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./TravisTest

after_script:
  - echo "Finished script..."

after_success:
  - echo "Congratulations, you didn't fuck up"
