dist: trusty
sudo: require

language: cpp
os: linux
compiler: gcc
  
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    #Test running script
    - export CC=gcc-7
    - export CXX=g++-7
    - gcc -v && g++ -v && cmake --version
    #return 0;

after_script:
    #deploy default Message
    - echo "Finished testing\n Results in "
after_success:
    #deploy Success message
    - echo "success"

after_failure:
    - echo "failure"
