/*||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||*/
/**
 * @file h
 * @author Marco "Swampy" Millan
 * @date 2018/10/17 2018
 * @brief Random number generator classes
 * 
 */
/*||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||*/
#pragma once
#include "nauMath.h"
#include "nauPrerequisitesUtil.h"
namespace nauEngineSDK {

 /**
  * nauRandomZ
  * Description:
  * 	Ziggurat algorithm random number generator
  * Sample usage:
  * 	
  */
class nauRandomZ
{
public:

  /**
   * Default Constructor
   */
  nauRandomZ() = default;

  /**
   * @brief Constructor with a seed generated by the user, a mean or a deviation
   * @param seed the seed to start, deviation = 1 as default, mean = 0 as default
   * @return a created RandomZ object
   *
   */
  nauRandomZ(float seed = 0, float deviation = 1.0f, float mean = 0.0f) 
    : m_seed(seed),
      m_deviation(deviation),
      m_mean(mean) {}

  float 
  next();

 public:

  float m_seed;
  float m_deviation;
  float m_mean;
};


}
