/*||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||*/
/**
 * @file h
 * @author Marco "Swampy" Millan
 * @date 2018/10/17 2018
 * @brief Random number generator classes, father and children:
 *  Ziggurat, Montecarlo and BoxMueller
 * 
 */
/*||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||°°°||*/
#pragma once
#include "nauMath.h"
#include "nauPrerequisitesUtil.h"
namespace nauEngineSDK {


  /**
   * nauRandom
   * Description:
   * 	Random father class
   * Sample usage:
   * 	list<nauRandom*> lets you have a list of all different children
   */
  class nauRandom
  {
   public:
    
    /**
     * Default constructor
     */
    nauRandom() = default;

    /**
     * Seed defining constructor
     */
    nauRandom(float nSeed) : m_seed(nSeed) {}

    /**
     * @brief calculate a new random and sets it as the next seed
     * @param 
     * @return the calculated random number
     *
     */
    virtual float
    next() = 0;

   public:
    /**
     * The seed to generate random numbers
     */
    float m_seed;

  };


  /**
   * nauRandomZ
   * Description:
   * 	Ziggurat algorithm random number generator
   * Sample usage:
   * 	
   */
  class nauRandomZ : public nauRandom
  {
   public:
  
    /**
     * Default Constructor
     */
    nauRandomZ() = default;
  
    /**
     * @brief Constructor with a seed generated by the user, a mean or a deviation
     * @param seed the seed to start, deviation = 1 as default, mean = 0 as default
     * @return a created RandomZ object
     *
     */
    nauRandomZ(float seed = 0, float deviation = 1.0f, float mean = 0.0f) 
      : nauRandom(seed),
        m_deviation(deviation),
        m_mean(mean) {}
    
    /**
     * @brief calculate a new random and sets it as the next seed
     * @param
     * @return the calculated random number
     *
     */
    float 
    next();

   public:
 
    /**
     * the deviation of the gaussian distribution
     */
    float m_deviation;

    /**
     * The mean of the gaussian distribution
     */
    float m_mean;
  };
  
  class nauRandomMC : public nauRandom
  {
   public:
  };
  
}
