/*0***0***0***0***0***0***0***0***0***0***0***0***0***0***0***0*/
/**
 * @file nauInput.h
 * @author Marco "Swampy" Millan
 * @date 2019/07/23 2019
 * @brief Input Object
 * 
 */
/*0***0***0***0***0***0***0***0***0***0***0***0***0***0***0***0*/
#pragma once

#include "nauPrerequisitesCore.h"

namespace nauEngineSDK 
{

namespace DEVICE
{
enum TYPE
{
  NONE                = 0,
  MOUSE               ,
  KEYBOARD            ,
  GAMEPAD             ,
  SENSOR
};
}

namespace JOYSTICK
{
enum E
{
  LEFT                = 0,
  RIGHT
};
}

namespace CONTROLLER
{
enum TYPE
{
  NONE                = 0,
  GENERIC             ,
  XBOX                ,
  PS1                 ,
  PS2                 ,
  PS3                 ,
  PS4                 ,
};
}

namespace AXIS
{
enum E
{
  HORIZONTAL          = 1 << 0,
  VERTICAL            = 1 << 1
};
}

namespace KEY
{
enum CODE
{
  ERRORED             = -1,
  NONE                = 0,
  INSERT              ,
  DELETEB             ,
  PAGEUP              ,
  PAGEDOWN            ,
  HOME                ,
  END                 ,
  KEYPAD0             ,
  KEYPAD1             ,
  KEYPAD2             ,
  KEYPAD3             ,
  KEYPAD4             ,
  KEYPAD5             ,
  KEYPAD6             ,
  KEYPAD7             ,
  KEYPAD8             ,
  KEYPAD9             ,
  KEYPADDOT           ,
  KEYPADENTER         ,
  KEYPADPLUS          ,
  KEYPADMINUS         ,
  KEYPADMULT          ,
  KEYPADDIV           ,
  KEYPADEQUAL         ,
  ARROWUP             ,
  ARROWDOWN           ,
  ARROWLEFT           ,
  ARROWRIGHT          ,
  BACKSPACE           ,
  RETURN              ,
  SPACE               ,
  LEFTSHIFT           ,
  RIGHTSHIFT          ,
  LEFTCONTROL         ,
  RIGHTCONTROL        ,
  ALT                 ,
  TAB                 ,
  CAPSLOCK            ,
  FN                  ,
  WINDOWS             ,
  ALTGR               ,
  COMMA               ,
  DOT                 ,
  ESCAPE              ,
  F1                  ,
  F2                  ,
  F3                  ,
  F4                  ,
  F5                  ,
  F6                  ,
  F7                  ,
  F8                  ,
  F9                  ,
  F10                 ,
  F11                 ,
  F12                 ,
  F13                 ,
  F14                 ,
  F15                 ,
  F16                 ,
  ALPHA0              ,
  ALPHA1              ,
  ALPHA2              ,
  ALPHA3              ,
  ALPHA4              ,
  ALPHA5              ,
  ALPHA6              ,
  ALPHA7              ,
  ALPHA8              ,
  ALPHA9              ,
  A                   ,
  B                   ,
  C                   ,
  D                   ,
  E                   ,
  F                   ,
  G                   ,
  H                   ,
  I                   ,
  J                   ,
  K                   ,
  L                   ,
  M                   ,
  N                   ,
  O                   ,
  P                   ,
  Q                   ,
  R                   ,
  S                   ,
  T                   ,
  U                   ,
  V                   ,
  W                   ,
  X                   ,
  Y                   ,
  Z                   ,
  MOUSEX              ,
  MOUSEY              ,
  MOUSE0              ,
  MOUSE1              ,
  MOUSE2              ,
  MOUSE3              ,
  MOUSE4              ,
  MOUSE5              ,
  MOUSE6              ,
  MOUSE7              ,
  MOUSE8              ,
  MOUSE9              ,
  MOUSE10             ,
  MOUSE11             ,
  MOUSE12             ,
  MOUSE13             ,
  MOUSE14             ,
  MOUSE15             ,
  MOUSE16             ,
  MOUSESCROLLDOWN     ,
  MOUSESCROLLUP       ,
  JOYSTICK0LEFTSTICKX ,
  JOYSTICK0LEFTSTICKY ,
  JOYSTICK0RIGHTSTICKX,
  JOYSTICK0RIGHTSTICKY,
  JOYSTICK0AXIS0      ,
  JOYSTICK0AXIS1      ,
  JOYSTICK0AXIS2      ,
  JOYSTICK0AXIS3      ,
  JOYSTICK0AXIS4      ,
  JOYSTICK0AXIS5      ,
  JOYSTICK0BUTTON0    ,
  JOYSTICK0BUTTON1    ,
  JOYSTICK0BUTTON2    ,
  JOYSTICK0BUTTON3    ,
  JOYSTICK0BUTTON4    ,
  JOYSTICK0BUTTON5    ,
  JOYSTICK0BUTTON6    ,
  JOYSTICK0BUTTON7    ,
  JOYSTICK0BUTTON8    ,
  JOYSTICK0BUTTON9    ,
  JOYSTICK0BUTTON10   ,
  JOYSTICK0BUTTON11   ,
  JOYSTICK0BUTTON12   ,
  JOYSTICK0BUTTON13   ,
  JOYSTICK0BUTTON14   ,
  JOYSTICK0BUTTON15   ,
  JOYSTICK0BUTTON16   ,
  JOYSTICK0BUTTON17   ,
  JOYSTICK0BUTTON18   ,
  JOYSTICK0BUTTON19   ,
  JOYSTICK1LEFTSTICKX ,
  JOYSTICK1LEFTSTICKY ,
  JOYSTICK1RIGHTSTICKX,
  JOYSTICK1RIGHTSTICKY,
  JOYSTICK1AXIS0      ,
  JOYSTICK1AXIS1      ,
  JOYSTICK1AXIS2      ,
  JOYSTICK1AXIS3      ,
  JOYSTICK1AXIS4      ,
  JOYSTICK1AXIS5      ,
  JOYSTICK1BUTTON0    ,
  JOYSTICK1BUTTON1    ,
  JOYSTICK1BUTTON2    ,
  JOYSTICK1BUTTON3    ,
  JOYSTICK1BUTTON4    ,
  JOYSTICK1BUTTON5    ,
  JOYSTICK1BUTTON6    ,
  JOYSTICK1BUTTON7    ,
  JOYSTICK1BUTTON8    ,
  JOYSTICK1BUTTON9    ,
  JOYSTICK1BUTTON10   ,
  JOYSTICK1BUTTON11   ,
  JOYSTICK1BUTTON12   ,
  JOYSTICK1BUTTON13   ,
  JOYSTICK1BUTTON14   ,
  JOYSTICK1BUTTON15   ,
  JOYSTICK1BUTTON16   ,
  JOYSTICK1BUTTON17   ,
  JOYSTICK1BUTTON18   ,
  JOYSTICK1BUTTON19   ,
  JOYSTICK2LEFTSTICKX ,
  JOYSTICK2LEFTSTICKY ,
  JOYSTICK2RIGHTSTICKX,
  JOYSTICK2RIGHTSTICKY,
  JOYSTICK2AXIS0      ,
  JOYSTICK2AXIS1      ,
  JOYSTICK2AXIS2      ,
  JOYSTICK2AXIS3      ,
  JOYSTICK2AXIS4      ,
  JOYSTICK2AXIS5      ,
  JOYSTICK2BUTTON0    ,
  JOYSTICK2BUTTON1    ,
  JOYSTICK2BUTTON2    ,
  JOYSTICK2BUTTON3    ,
  JOYSTICK2BUTTON4    ,
  JOYSTICK2BUTTON5    ,
  JOYSTICK2BUTTON6    ,
  JOYSTICK2BUTTON7    ,
  JOYSTICK2BUTTON8    ,
  JOYSTICK2BUTTON9    ,
  JOYSTICK2BUTTON10   ,
  JOYSTICK2BUTTON11   ,
  JOYSTICK2BUTTON12   ,
  JOYSTICK2BUTTON13   ,
  JOYSTICK2BUTTON14   ,
  JOYSTICK2BUTTON15   ,
  JOYSTICK2BUTTON16   ,
  JOYSTICK2BUTTON17   ,
  JOYSTICK2BUTTON18   ,
  JOYSTICK2BUTTON19   ,
  JOYSTICK3LEFTSTICKX ,
  JOYSTICK3LEFTSTICKY ,
  JOYSTICK3RIGHTSTICKX,
  JOYSTICK3RIGHTSTICKY,
  JOYSTICK3AXIS0      ,
  JOYSTICK3AXIS1      ,
  JOYSTICK3AXIS2      ,
  JOYSTICK3AXIS3      ,
  JOYSTICK3AXIS4      ,
  JOYSTICK3AXIS5      ,
  JOYSTICK3BUTTON0    ,
  JOYSTICK3BUTTON1    ,
  JOYSTICK3BUTTON2    ,
  JOYSTICK3BUTTON3    ,
  JOYSTICK3BUTTON4    ,
  JOYSTICK3BUTTON5    ,
  JOYSTICK3BUTTON6    ,
  JOYSTICK3BUTTON7    ,
  JOYSTICK3BUTTON8    ,
  JOYSTICK3BUTTON9    ,
  JOYSTICK3BUTTON10   ,
  JOYSTICK3BUTTON11   ,
  JOYSTICK3BUTTON12   ,
  JOYSTICK3BUTTON13   ,
  JOYSTICK3BUTTON14   ,
  JOYSTICK3BUTTON15   ,
  JOYSTICK3BUTTON16   ,
  JOYSTICK3BUTTON17   ,
  JOYSTICK3BUTTON18   ,
  JOYSTICK3BUTTON19   ,
  JOYSTICK4LEFTSTICKX ,
  JOYSTICK4LEFTSTICKY ,
  JOYSTICK4RIGHTSTICKX,
  JOYSTICK4RIGHTSTICKY,
  JOYSTICK4AXIS0      ,
  JOYSTICK4AXIS1      ,
  JOYSTICK4AXIS2      ,
  JOYSTICK4AXIS3      ,
  JOYSTICK4AXIS4      ,
  JOYSTICK4AXIS5      ,
  JOYSTICK4BUTTON0    ,
  JOYSTICK4BUTTON1    ,
  JOYSTICK4BUTTON2    ,
  JOYSTICK4BUTTON3    ,
  JOYSTICK4BUTTON4    ,
  JOYSTICK4BUTTON5    ,
  JOYSTICK4BUTTON6    ,
  JOYSTICK4BUTTON7    ,
  JOYSTICK4BUTTON8    ,
  JOYSTICK4BUTTON9    ,
  JOYSTICK4BUTTON10   ,
  JOYSTICK4BUTTON11   ,
  JOYSTICK4BUTTON12   ,
  JOYSTICK4BUTTON13   ,
  JOYSTICK4BUTTON14   ,
  JOYSTICK4BUTTON15   ,
  JOYSTICK4BUTTON16   ,
  JOYSTICK4BUTTON17   ,
  JOYSTICK4BUTTON18   ,
  JOYSTICK4BUTTON19   ,
  JOYSTICK5LEFTSTICKX ,
  JOYSTICK5LEFTSTICKY ,
  JOYSTICK5RIGHTSTICKX,
  JOYSTICK5RIGHTSTICKY,
  JOYSTICK5AXIS0      ,
  JOYSTICK5AXIS1      ,
  JOYSTICK5AXIS2      ,
  JOYSTICK5AXIS3      ,
  JOYSTICK5AXIS4      ,
  JOYSTICK5AXIS5      ,
  JOYSTICK5BUTTON0    ,
  JOYSTICK5BUTTON1    ,
  JOYSTICK5BUTTON2    ,
  JOYSTICK5BUTTON3    ,
  JOYSTICK5BUTTON4    ,
  JOYSTICK5BUTTON5    ,
  JOYSTICK5BUTTON6    ,
  JOYSTICK5BUTTON7    ,
  JOYSTICK5BUTTON8    ,
  JOYSTICK5BUTTON9    ,
  JOYSTICK5BUTTON10   ,
  JOYSTICK5BUTTON11   ,
  JOYSTICK5BUTTON12   ,
  JOYSTICK5BUTTON13   ,
  JOYSTICK5BUTTON14   ,
  JOYSTICK5BUTTON15   ,
  JOYSTICK5BUTTON16   ,
  JOYSTICK5BUTTON17   ,
  JOYSTICK5BUTTON18   ,
  JOYSTICK5BUTTON19   ,
  JOYSTICK6LEFTSTICKX ,
  JOYSTICK6LEFTSTICKY ,
  JOYSTICK6RIGHTSTICKX,
  JOYSTICK6RIGHTSTICKY,
  JOYSTICK6AXIS0      ,
  JOYSTICK6AXIS1      ,
  JOYSTICK6AXIS2      ,
  JOYSTICK6AXIS3      ,
  JOYSTICK6AXIS4      ,
  JOYSTICK6AXIS5      ,
  JOYSTICK6BUTTON0    ,
  JOYSTICK6BUTTON1    ,
  JOYSTICK6BUTTON2    ,
  JOYSTICK6BUTTON3    ,
  JOYSTICK6BUTTON4    ,
  JOYSTICK6BUTTON5    ,
  JOYSTICK6BUTTON6    ,
  JOYSTICK6BUTTON7    ,
  JOYSTICK6BUTTON8    ,
  JOYSTICK6BUTTON9    ,
  JOYSTICK6BUTTON10   ,
  JOYSTICK6BUTTON11   ,
  JOYSTICK6BUTTON12   ,
  JOYSTICK6BUTTON13   ,
  JOYSTICK6BUTTON14   ,
  JOYSTICK6BUTTON15   ,
  JOYSTICK6BUTTON16   ,
  JOYSTICK6BUTTON17   ,
  JOYSTICK6BUTTON18   ,
  JOYSTICK6BUTTON19   ,
  JOYSTICK7LEFTSTICKX ,
  JOYSTICK7LEFTSTICKY ,
  JOYSTICK7RIGHTSTICKX,
  JOYSTICK7RIGHTSTICKY,
  JOYSTICK7AXIS0      ,
  JOYSTICK7AXIS1      ,
  JOYSTICK7AXIS2      ,
  JOYSTICK7AXIS3      ,
  JOYSTICK7AXIS4      ,
  JOYSTICK7AXIS5      ,
  JOYSTICK7BUTTON0    ,
  JOYSTICK7BUTTON1    ,
  JOYSTICK7BUTTON2    ,
  JOYSTICK7BUTTON3    ,
  JOYSTICK7BUTTON4    ,
  JOYSTICK7BUTTON5    ,
  JOYSTICK7BUTTON6    ,
  JOYSTICK7BUTTON7    ,
  JOYSTICK7BUTTON8    ,
  JOYSTICK7BUTTON9    ,
  JOYSTICK7BUTTON10   ,
  JOYSTICK7BUTTON11   ,
  JOYSTICK7BUTTON12   ,
  JOYSTICK7BUTTON13   ,
  JOYSTICK7BUTTON14   ,
  JOYSTICK7BUTTON15   ,
  JOYSTICK7BUTTON16   ,
  JOYSTICK7BUTTON17   ,
  JOYSTICK7BUTTON18   ,
  JOYSTICK7BUTTON19   ,
  LASTINPUT           ,
};
}

}

